### ISSUE TITLE
[Suggestion] mod-configurations

### ISSUE THREAD

**Issue by Serpens66** [LemonDrop1228/AMM-Source-Code#6]
Hi :)
I was redirected here to ask for mod settings, please see here:
https://github.com/anno-mods/Anno/issues/9#issue

**Comment by dianaw353** [comment]
ya its already planned... 99% sure
you can see the AMM info here and the roadmap [AMM Wiki](https://www.notion.so/Anno-1800-Mod-Manager-Wiki-60bbcd8ad9634c2faa225be3f1bd46d6)

**Comment by Serpens66** [comment]
thanks.
just to be sure:
is your project "only" a mod manager, or does it also include a (maybe improved) mod loader?
Because I think such modsettings should belong to the mod loader. So I wonder if I should also suggest this to the mod loader repo (so many repos :D)

**Comment by dianaw353** [comment]
uhh... this is only a Mod manager. The mod loader just allows mods to communicate to the anno 1800

**Comment by Serpens66** [comment]
> 
> 
> uhh... this is only a Mod manager. The mod loader just allows mods to be work in anno 1800 nothing else

thanks for the fast reply.
I thought about this functionality:
The user should be able to define eg. a custom value (any integer he wants). This value is then stored somewhere, and when the loader injects the mod xml into the assets.xml from the game, it enters the value of this variable (for example as new gold cost for every item, or sth like that)

Now the question is:
Where should the user enter this value? When starting the mod loader? Or whould this be part of a mod manager, which would require the manager and the loader to work together.

**Comment by dianaw353** [comment]
The mod manager and the mod loader does not work together. So you would just edit the x value and then it saves to that mod and then the game just loads it that way. (not sure if that made any sense lol)

**Comment by Serpens66** [comment]
hm.. I'm not quite into mod loader/manager, but my first impression would be that it is mandatory that at least the authors of loader and manager work together, to not do the same tasks twice. Just skimming through the issues of mod loader and eg. this would be sth. that a mod manager should deal with:
https://github.com/xforce/anno1800-mod-loader/issues/39

Anyway, I will post my suggestion on the mod loader, thank you very much for your time and work :)

**Comment by dianaw353** [comment]
all the work that goes into it goes to lemendrop

**Comment by dianaw353** [comment]
![mods2](https://user-images.githubusercontent.com/65094216/94978171-63942680-04d9-11eb-8cce-bee48aa531a2.PNG)
This is to show you how mods work in general. ya i know its from a different game but they pretty much run the same way...
